services:
  coder-web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:3000" 
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:./prisma/dev.db
      - PORT=3000
      - HOSTNAME=0.0.0.0
    volumes:
      - /opt/coder-web/data/prisma/dev.db:/app/prisma/dev.db
      - /opt/coder-web/data/uploads:/app/data
      - /opt/coder-web/logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - coder-web
    restart: unless-stopped
    profiles:
      - nginx